{"uuid": "56fa5d9b-4094-4c47-9f32-24a24b63ece9", "children": ["1c08510e-38f2-448a-b921-6766debd78bf"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: MicrosoftEdge=138.0.3351.121)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7ccd382b5+23461]\n\t(No symbol) [0x0x7ff7ccc8c3a0]\n\tGetHandleVerifier [0x0x7ff7ccfb01e8+2611928]\n\t(No symbol) [0x0x7ff7cca5a250]\n\t(No symbol) [0x0x7ff7cca4e4ff]\n\t(No symbol) [0x0x7ff7cca4fb66]\n\t(No symbol) [0x0x7ff7cca4e769]\n\t(No symbol) [0x0x7ff7cca4e36c]\n\t(No symbol) [0x0x7ff7cca4e0b8]\n\t(No symbol) [0x0x7ff7cca4c0b9]\n\t(No symbol) [0x0x7ff7cca4c68c]\n\t(No symbol) [0x0x7ff7cca6057a]\n\t(No symbol) [0x0x7ff7ccae7ade]\n\t(No symbol) [0x0x7ff7ccaca6ba]\n\t(No symbol) [0x0x7ff7cca9f58d]\n\t(No symbol) [0x0x7ff7ccae754f]\n\t(No symbol) [0x0x7ff7ccaca423]\n\t(No symbol) [0x0x7ff7cca9ea86]\n\t(No symbol) [0x0x7ff7cca9dd11]\n\t(No symbol) [0x0x7ff7cca9e8b3]\n\t(No symbol) [0x0x7ff7ccb9dd3d]\n\t(No symbol) [0x0x7ff7ccbab0c8]\n\tGetHandleVerifier [0x0x7ff7cce180fb+940523]\n\tGetHandleVerifier [0x0x7ff7cce20e51+976705]\n\t(No symbol) [0x0x7ff7ccc99f91]\n\t(No symbol) [0x0x7ff7ccc92974]\n\t(No symbol) [0x0x7ff7ccc92ac3]\n\t(No symbol) [0x0x7ff7ccc84566]\n\tBaseThreadInitThunk [0x0x7ffaff35259d+29]\n\tRtlUserThreadStart [0x0x7ffaff66af78+40]\n\n", "trace": "  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject_Handson\\Test_Automation_Framework\\HybridFramework\\DataDrivenTesting_8\\Cases\\conftest.py\", line 20, in setup_teardown\n    driver.get(ReadConfigurations.read_configuration(\"INFO\", \"link\"))\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 389, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mahesh.Shendge\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754230786587, "stop": 1754230790627}], "start": 1754230786587, "stop": 1754230790994}